housing_data <- read.csv("housing_data.csv")
network_backup_dataset <- read.csv("network_backup_dataset.csv")
install.packages("ggplot2")
library('ggplot2')
install.packages("lattice")
library('lattice')
install.packages("DAAG")
library('DAAG')
install.packages("randomForest")
library('randomForest')
install.packages("neuralnet")
library("neuralnet")
#install.packages("usdm")
#library('usdm')
install.packages("MASS")
library('MASS')
install.packages("glmnet")
library('glmnet')
install.packages("lars")
library('lars')
install.packages("data.table")
library(data.table)
install.packages("gtools")
library(gtools)
install.packages("usdm")
library(usdm)
